### ISSUE TITLE
URN ist ein Typ von idno

### ISSUE THREAD

**Issue by GVogeler** [stefanieschoeberl/Dig_Ed_Himmlisches_Jerusalem#3]
In https://github.com/stefanieschoeberl/Dig_Ed_Himmlisches_Jerusalem/blob/ac6322879a706f0b17c293b94700007e06b0dffb/HimmlJer_Transcript.xml#L30 geben Sie die URN als "Quelle" der Signatur an. Das ist so eine Fehlinterpretation der TEI. Sie können in https://github.com/stefanieschoeberl/Dig_Ed_Himmlisches_Jerusalem/blob/ac6322879a706f0b17c293b94700007e06b0dffb/HimmlJer_Transcript.xml#L35 der `idno` einen `@type="URN"` hinzufügen, der das besser ausdrückt.

**Comment by stefanieschoeberl** [comment]
wie vorgeschlagen angepasst
