### ISSUE TITLE
@facs könnte auch mehrere Zonen referenzieren.

### ISSUE THREAD

**Issue by GVogeler** [stefanieschoeberl/Dig_Ed_Himmlisches_Jerusalem#4]
In https://github.com/stefanieschoeberl/Dig_Ed_Himmlisches_Jerusalem/blob/ac6322879a706f0b17c293b94700007e06b0dffb/HimmlJer_Transcript.xml#L967-L976 haben Sie sich dafür entschieden, eine Lösung für überlappendes Markup anzuwenden (`@part`), um die Strophe, die über den Seitenwechsel hinweg reicht, zu kodieren. Das ist prinzipiell möglich. Alternativ kann man aber auch mehrere Zonen in einem `@facs` Attribut referenzieren (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.global.facs.html : Datentype `1–∞ occurrences of [teidata.pointer](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-teidata.pointer.html) separated by whitespace`) was die Kodierung der Textstruktur erleichtern würde.

**Comment by stefanieschoeberl** [comment]
angepasst in Strophen 5, 9, 13, 16, 20, 24, 28 (dass @facs mehrere Werte haben kann, hatte ich nicht bedacht - macht aber vieles einfacher)
- dafür eingefügt: `<cb>` und `<pb>` mit @n zur Orientierung
